controller_joint_names: ['', 'Thigh4_Joint', 'Shin4_Joint', 'Foot4_Joint', 'Thigh3_Joint', 'Shin3_Joint', 'Foot3_Joint', 'Thigh2_Joint', 'Shin2_Joint', 'Foot2_Joint', 'Thigh1_Joint', 'Shin1_Joint', 'Foot1_Joint', ]
